apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- istio-rollout-ns.yaml
- istio-rollout.yaml
- istio-rollout-svc.yaml
- istio-rollout-vsvc.yaml
- istio-rollout-gateway.yaml
- istio-success-rate-analysis.yaml